apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb
        image: ftavares/rpi-mongo:3.0.9
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 27017
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongodata
            mountPath: "/data/db"
      volumes:
      - name: mongodata
        persistentVolumeClaim:
          claimName: mongodata