apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodata
  labels:
    volume: mongodata
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/mongodb
  # nfs:
  #   host: 192.168.0.120
  #   exports: /cluster-data