kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodata
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: mongodata
