apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    db: mongo
spec:
  containers:
    - image: ftavares/rpi-mongo:3.0.9
      name: db
      ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
