apiVersion: v1
kind: Pod
metadata:
  name: preguntas
  labels:
    app: preguntas
spec:
  containers:
    - image: dockercochabamba/2-bday-preguntas-arm:v1
      name: preguntas
      env:
        - name: DB_ADDRESS
          value: mongodb://db:27017
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
